Migrated verizon adapter to yahoo mobile sdk.
AppLovin/AppLovin-MAX-SDK-Android pull request #287
Opened 2022-03-29 19:50 UTC by kristiankuhn

In order for this adapter to work with AppLovin you will need to create a class com.verizon.ads.VASAds.java in the sample app project so that the AppLovin SDK thinks the Verizon SDK is present. The Yahoo Mobile SDK is what is driving the adapter but the old class is how AppLovin verifies Verizon Ads is library is present so we have to fake it to get the adapter configured successfully.

2022-03-29 20:41 UTC, thomasmso commented
Thanks for the PR - we're testing their new SDK internally and will provide updates when released.

2022-03-29 21:06 UTC, kristiankuhn commented
Don't merge this. It's a preview of what is needed to use Yahoo Mobile SDK which is a replacement for Verizon Ads and will be released shortly.

2022-03-29 21:27 UTC, thomasmso commented
For sure. Thank you once again for this PR for us to reference.

2022-04-19 13:55 UTC, kristiankuhn commented
@thomasmso I've updated the PR to the GA release of Yahoo Mobile SDK. I see there is a merge conflict with the adapter but it's probably not worth resolving as the adapters are completely different between Verizon Ads and Yahoo Mobile. With that said what is your plan for supporting Verizon? Do you intend to support both SDKs for some period of time? In that case we may need to make a new Yahoo adapter and leave the Verizon one as it is. This would apply to both Android and iOS so please advise. Thank you

2022-04-19 22:24 UTC, thomasmso commented
We are going to just update the current adapter with the new code.

2022-05-02 20:48 UTC, tiandrew requested changes

2022-05-02 20:48 UTC, tiandrew commented on VerizonAds/src/main/java/com/applovin/mediation/adapters/VerizonAdsMediationAdapter.java
> +        YASAds.setLogLevel( Logger.VERBOSE );
We should use the log level defined above here

2022-05-02 20:48 UTC, tiandrew commented on VerizonAds/src/main/java/com/applovin/mediation/adapters/VerizonAdsMediationAdapter.java
> +    private class InterstitialListener implements InterstitialAd.InterstitialAdListener
Could you run auto-formatting on this file? `implements` should be on a new line

2022-05-02 20:48 UTC, tiandrew commented on VerizonAds/src/main/java/com/applovin/mediation/adapters/VerizonAdsMediationAdapter.java
> +//            inlineAdView.setRefreshInterval( Integer.MAX_VALUE );
Does this method work still? If so we should probably set it

2022-05-02 20:48 UTC, tiandrew commented on VerizonAds/src/main/java/com/applovin/mediation/adapters/VerizonAdsMediationAdapter.java
> +                if (titleComponent != null) {
Auto-formatting

2022-05-02 20:48 UTC, tiandrew commented on VerizonAds/src/main/java/com/applovin/mediation/adapters/VerizonAdsMediationAdapter.java
> +                }
We can remove these checks, we're only doing them for template ads now, so you can also just combine this with the case below and remove `missingRequiredAssets`

2022-05-02 20:48 UTC, tiandrew commented on VerizonAds/src/main/java/com/applovin/mediation/adapters/VerizonAdsMediationAdapter.java
> +
```suggestion
```

2022-05-02 20:48 UTC, tiandrew commented on VerizonAds/src/main/java/com/applovin/mediation/adapters/VerizonAdsMediationAdapter.java
> +            nativeAd.registerContainerView(maxNativeAdView);
Could you check if multiple native ads using the same recycled `MaxNativeAdView` will allow clicks to work for all the views? We had this issue previously with Verizon's native ads so just want to make sure they fixed it

2022-05-02 20:56 UTC, tiandrew commented
Sorry for the confusion, please ignore the requested changes, closing this one; we're iterating on changes internally.

2022-05-19 19:47 UTC, thomasmso commented
Adapter is live: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/commit/96c697185bc8a1b5bffc86ac0abb566b2729a9f3

2022-05-19 19:47 UTC, closed without merging