feat/jetpack_compose_integration
AppLovin/AppLovin-MAX-SDK-Android pull request #530
Opened 2023-07-28 18:47 UTC by mattn02

https://app.asana.com/0/573104092700345/1203989763933177/f

## Overview

This PR demos how to integrate the following ad formats using Kotlin's Jetpack Compose:

**AppLovin network ads:**
- Banner/Leader
- MREC
- Rewarded
- Interstitial

**MAX mediated ads:**
- Banner/Leader
- MREC
- App Open
- Interstitial
- Native ads using Templates API

## Testing

- Tested on local test device (Galaxy S20) using ad unit & application IDs from Test App.
- Used Profiler in Android Studios to ensure that no memory leaks occurred in new features.

2023-07-29 00:16 UTC, Lorenzo45 requested changes

2023-07-29 00:16 UTC, Lorenzo45 commented on AppLovin MAX Demo App - Kotlin/app/src/main/java/com/applovin/enterprise/apps/demoapp/ads/max/interstitial/JetpackComposeInterstitialAdActivity.kt
I actually misspoke in the Asana ticket description - we don't need Jetpack Compose integrations for _all_ of our ad formats. We really only need it for banners/leaders, MRECs, and native ads - we can skip fullscreen ad formats (interstitial, rewarded, app open).

Showing fullscreen ads just require API calls, but banners/MRECs/native ads are actually a part of the UI so Jetpack Compose demos make more sense there.

Could we remove all the fullscreen ad integrations to keep the PR clean and keep our demo app slimmer?

Looks like you got a lot of cool experience learning how to build Jetpack compose UI and display all our ad formats at least :)

2023-07-29 00:16 UTC, Lorenzo45 commented on AppLovin MAX Demo App - Kotlin/app/build.gradle
> +    debugImplementation 'androidx.compose.ui:ui-test-manifest'
You think we can remove any of these dependencies? We generally try to have as few dependencies as possible.

2023-07-29 00:38 UTC, Lorenzo45 commented
Also great to see you're already using the Android Studio profiler to check for memory leaks :)

2023-08-02 21:54 UTC, mattn02 commented
Changes made. Removed Jetpack Compose integration for fullscreen ads + cleaned up dependencies in gradle file

2023-08-04 18:17 UTC, mattn02 commented
Changes made: ensured Jetpack Compose features worked correctly with workspace environment & cleaned up changes in manifest to make PR slimmer.

I updated the packages for the MAX full screen ads (app open, rewarded, interstitial) after removing the jetpack compose integration since [the current one in master doesn't fully reflect the file location that they are in](https://github.com/AppLovin/AppLovin-MAX-SDK-Android/blob/dbc5fdedbb1479357945e6e3034d502a9951dbbc/AppLovin%20MAX%20Demo%20App%20-%20Kotlin/app/src/main/java/com/applovin/enterprise/apps/demoapp/ads/max/AppOpenAdActivity.kt#L1). Let me know if I should keep these changes or revert it back.

2023-08-04 19:22 UTC, avi-cramer reviewed
Looks good, just a couple minor UI change requests:

- Could we get the "Load" button for AppLovin jetpack compose banners/mrecs to look more in line with the other activities? It is currently a little smaller and doesn't fit the color theme of the app.
- Indentation when we log the callbacks to match the other activities (for MAX and AppLovin activities)
- Jetpack Compose Native ads "Show Ad" button could use some margin on the bottom to match other activities
- Jetpack Compose Native ads are not displaying the same as normal Templates API, looks like the native ad is rendered in a box whereas for normal Templates API the ad is using the full screen width

2023-08-11 20:52 UTC, mattn02 commented
Changes made! Adjusted UI to match with rest of demo app + revamped architecture to follow MVVM convention as used in iOS PR :)

2023-08-18 02:08 UTC, avi-cramer approved these changes
Looks good to me!

2023-08-18 02:08 UTC, avi-cramer commented on AppLovin MAX Demo App - Kotlin/app/src/main/java/com/applovin/enterprise/apps/demoapp/ads/max/RewardedAdActivity.kt
> +
```suggestion
```

2023-08-24 20:13 UTC, Lorenzo45 approved these changes
Looks super clean overall! I think the view model architecture is great. Nice work :)

2023-08-24 20:13 UTC, Lorenzo45 commented on AppLovin MAX Demo App - Kotlin/app/build.gradle
> +    implementation 'androidx.compose.foundation:foundation:1.3.0'
Thanks for slimming down the dependencies 👍 One small nit is that the `() " '` usages are inconsistent

2023-08-24 20:13 UTC, Lorenzo45 commented on AppLovin MAX Demo App - Kotlin/app/src/main/java/com/applovin/enterprise/apps/demoapp/ads/applovin/banners/BannerJetpackComposeActivity.kt
> +        viewModel = AppLovinAdViewComposableViewModel(this)
nit: `viewModel` is pretty generic, would be good to specify that this is an `bannerViewModel` or something (same comment applies to the other Activities)

2023-08-25 00:03 UTC, mattn02 commented
Changes made!

2023-09-30 23:32 UTC, thomasmso approved these changes

2023-10-06 23:52 UTC, merged