feat/update_demo_app_tracking_with_adjust_sdk
AppLovin/AppLovin-MAX-SDK-Android pull request #59
Opened 2021-12-03 01:11 UTC by Billy-Hu

2021-12-03 01:17 UTC, thomasmso requested changes

2021-12-03 01:17 UTC, thomasmso commented on AppLovin MAX Demo App - Java/app/src/main/java/com/applovin/enterprise/apps/demoapp/GlobalApplication.java
> +            String appToken = "{YourAppToken}";
```suggestion
        AppLovinSdk.getInstance( this ).initializeSdk( config -> {
        
            // AppLovin SDK is initialized, start loading ads now or later if ad gate is reached
            
            // Set up Adjust SDK
            String appToken = "{YourAppToken}";
```

2021-12-03 01:17 UTC, thomasmso commented on AppLovin MAX Demo App - Kotlin/app/src/main/AndroidManifest.xml
> +            android:value="hBDh6tzZrp-fWye63N4nhbgw8umnTzD99QsGIpq8bpo7lRDppHZVuEQ17Bpa80lIRaTlONt-Af6v5JiubGOUVp" />
No need to check our SDK key

2021-12-03 01:17 UTC, thomasmso commented on AppLovin MAX Demo App - Kotlin/app/src/main/java/com/applovin/enterprise/apps/demoapp/GlobalApplication.kt
> +            val appToken = "{YourAppToken}"
```suggestion
        AppLovinSdk.getInstance(this).initializeSdk {
            
            // AppLovin SDK is initialized, start loading ads now or later if ad gate is reached

            // Set up Adjust SDK
            val appToken = "{YourAppToken}"
```

2021-12-03 01:17 UTC, thomasmso commented on AppLovin MAX Demo App - Kotlin/app/src/main/java/com/applovin/enterprise/apps/demoapp/GlobalApplication.kt
> +        override fun onActivityCreated(p0: Activity, p1: Bundle?) {}
We should give these parameters better names, like we did in Java.

2021-12-06 19:54 UTC, Billy-Hu commented
Changes made

2021-12-06 20:33 UTC, thomasmso commented on AppLovin MAX Demo App - Java/app/src/main/java/com/applovin/enterprise/apps/demoapp/GlobalApplication.java
> +            Adjust.onCreate( adjustConfig );
Let's inline params and keep comment consistent with iOS, and no need for verbose log setting
```suggestion
            // Initialize Adjust SDK
            AdjustConfig adjustConfig = new AdjustConfig( getApplicationContext(), "{YourAppToken}", AdjustConfig.ENVIRONMENT_SANDBOX );
            Adjust.onCreate( adjustConfig );
```

2021-12-06 20:33 UTC, thomasmso commented on AppLovin MAX Demo App - Kotlin/app/src/main/java/com/applovin/enterprise/apps/demoapp/GlobalApplication.kt
> +            Adjust.onCreate(config)
```suggestion
            // Initialize Adjust SDK
            val config = AdjustConfig(this, "{YourAppToken}", AdjustConfig.ENVIRONMENT_SANDBOX)
            Adjust.onCreate(config)
```

2021-12-06 21:37 UTC, Billy-Hu commented
Changes made

2021-12-06 22:47 UTC, thomasmso approved these changes

2021-12-06 22:47 UTC, thomasmso commented on AppLovin MAX Demo App - Java/app/src/main/java/com/applovin/enterprise/apps/demoapp/GlobalApplication.java
> +            Adjust.onCreate( adjustConfig );
```suggestion
            // Initialize Adjust SDK
            AdjustConfig adjustConfig = new AdjustConfig( getApplicationContext(), "{YourAppToken}", AdjustConfig.ENVIRONMENT_SANDBOX );
            Adjust.onCreate( adjustConfig );
```

2021-12-06 22:47 UTC, thomasmso commented on AppLovin MAX Demo App - Kotlin/app/src/main/java/com/applovin/enterprise/apps/demoapp/GlobalApplication.kt
> +            // set up Adjust SDK
```suggestion
            // Initialize Adjust SDK
```

2021-12-06 22:48 UTC, thomasmso approved these changes

2021-12-07 18:34 UTC, merged